# This spection specifies the data that will be input into the model
data:
  # Specify the dataset file
  resource: ~/dockerimages/QSARTuna/PXR/train.csv 
  type: intake
  input_col: SMILES 
  # Specify each (1+) of the target columns, or the column that you're trying to predict
  target_cols:
  - pEC50
  dropna: true

# Additional metadata
# This should be descriptive as the tags in these fields will annotate downstream Anvil processes:
# mainly, when you do model inference
metadata:
  authors: Sandeep Pal 
  email: spal@cheminfosolutions.co.uk 
  biotargets:
  - CYP3A4
  build_number: 0
  description: basic regression using a LightGBM model
  driver: sklearn
  name: lgbm_pchembl
  tag: pxr 
  tags:
  - openadmet
  - test
  - pchembl
  version: v1

# Section specifying training procedure:
# What model will you use?
# What featurizers will the model use?
# What hyperparameters will the mdoel use?
procedure:
# Featurization specification
  feat:
    # Using concatenated features, which combines multiple featurizers
    # here we use DescriptorFeaturizer and FingerprintFeaturizer for 2D RDKit descriptors and ECFP4 fingerprints
    # See openadmet.models.features
    type: FeatureConcatenator
    # Add parameters for the featurizer. Full description of the featurizer options are in Section 5.
    params:
      featurizers:
        DescriptorFeaturizer:
          descr_type: "desc2d"
        FingerprintFeaturizer:
          fp_type: "ecfp:4"

  # Model specification
  model:
    # Indicate model type
    # See openadmet.models.architecture for all model types
    type: LGBMRegressorModel
    # Specify model parameters
    params:
      alpha: 0.005
      learning_rate: 0.05
      n_estimators: 500


  # Specify data splits
  split:
    # Specify how data will be split
    # See openadmet.models.split
    type: ShuffleSplitter
    # Specify split parameters
    params:
      random_state: 42
      train_size: 0.8
      val_size: 0.0 # For LGBM, no validation set is needed
      test_size: 0.2 # If you want to compare tree-based models with Dl models later, the test sizes should match

  # Specify training configuration
  train:
    # Specify the trainer, here SKLearnBasicTrainer as model has an sklearn interface
    # could also use SKLearnGridSearchTrainer for hyperparameter tuning
    type: SKLearnBasicTrainer


# Section specifying report generation
# What cross validation splits will you use?
# You can also specify the min and max values of your plots
report:
  # Configure evaluation
  eval:
  # Generate regression metrics
  - type: RegressionMetrics
    params: {}
  # Generate regression plots & do cross validation
  - type: SKLearnRepeatedKFoldCrossValidation
    params:
      axes_labels:
      - True pEC50
      - Predicted pEC50
      max_val: 10
      min_val: 1 
      pXC50: true
      n_splits: 5
      n_repeats: 5
      title: True vs Predicted pEC50 on test set
